language: node_js
sudo: false
dist: trusty
node_js:
  - "8"

install:  
  - npm i ionic -g
  - npm i
  
script:
  - npm test

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - ionic serve &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 10
