language: node_js
sudo: required
node_js:
  - "6"
  - "7"

install:
  - npm i
  - npm i ionic -g
  
script:
  - npm test

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - ionic serve &